# Site settings
title: pierstu
email: pierre.studievic@pm.me
description: "pierre s - balises, logiciels libres, synth diy ..."
baseurl: ""
url: "http://pierstu.github.io"
mastodon_username: pierstu
diaspora_username: pierstu 
github_username:  pierstu
myspace_username: pierstu

# Collections
collections: 
 - dates
 - publications

# Build settings
sass:
 sass_dir: _sass
include: ['_pages']
markdown: kramdown
permalink: pretty
