# Site settings
title: pierstu
email: pierstu@free.fr
description: "pierre s - balises, logiciels libres, synth diy ..."
baseurl: ""
url: "http://pierstu.github.io"
diaspora_username: pierstu
github_username:  pierstu

# Collections
collections: 
 - dates
 - publications

# Build settings
sass:
 sass_dir: _sass
include: ['_pages']
markdown: kramdown
permalink: pretty
