# Site settings
title: pierstu
email: pierstu@free.fr
description: "pierre s - ordinateurs, bricole, balises, logiciels libres, musique ou presque"
baseurl: ""
url: "http://localhost:4000"
diaspora_username: pierstu
github_username:  pierstu

# Collections
collections: 
 - dates
 - publications

# Build settings
sass:
 sass_dir: _sass
include: ['_pages']
markdown: kramdown
permalink: pretty
